version: '3'

services:
  app:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'demo'
      MYSQL_USER: 'demo'
      MYSQL_PASSWORD: '123456'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - $PWD/data:/var/lib/mysql
